# Generated by Django 5.2 on 2025-04-22 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('waste_source_group', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tier', models.CharField(choices=[('tier_1', 'Tier 1'), ('tier_2', 'Tier 2'), ('tier_3', 'Tier 3'), ('tier_4', 'Tier 4')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Generator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('address_line_1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pin_code', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('contact_email', models.EmailField(max_length=254, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('Waste_generator_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='waste_source_group.wastegeneratorgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WasteSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('waste_type', models.CharField(max_length=50)),
                ('food_type', models.CharField(max_length=50)),
                ('waste_weight', models.FloatField()),
                ('generator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste_generators.generator')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WasteSourceMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=1)),
                ('waste_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste_source_group.wastegroupmaster')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='generator',
            name='waste_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='waste_generators.wastesourcemaster'),
        ),
        migrations.CreateModel(
            name='WasteSourceSpecificationMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specification', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=1)),
                ('waste_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste_generators.wastesourcemaster')),
            ],
        ),
        migrations.AddField(
            model_name='generator',
            name='waste_source_specification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='waste_generators.wastesourcespecificationmaster'),
        ),
    ]
