# Generated by Django 5.2 on 2025-04-22 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_generators', '0001_initial'),
        ('waste_source_group', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wastesourcemaster',
            name='name',
        ),
        migrations.AddField(
            model_name='wastesourcemaster',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='wastesourcemaster',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='wastesourcemaster',
            name='waste_source',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='waste_source_group.mastersource'),
            preserve_default=False,
        ),
    ]
