# Generated by Django 5.2 on 2025-04-22 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_generators', '0002_remove_wastesourcemaster_name_and_more'),
        ('waste_source_group', '0003_mastersource_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastesourcemaster',
            name='waste_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste_source_group.wastegeneratorgroup'),
        ),
    ]
