# Generated by Django 5.2 on 2025-04-23 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('waste_generators', '0003_alter_wastesourcemaster_waste_group'),
        ('waste_source_group', '0003_mastersource_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WastePickUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pickup_date', models.DateField()),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='waste_pickup')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste_source_group.masterdestination')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='GeneratorType',
        ),
        migrations.AlterField(
            model_name='wastesource',
            name='waste_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.commoditygroup'),
        ),
        migrations.AlterField(
            model_name='wastesource',
            name='food_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste_generators.foodtype'),
        ),
        migrations.AddField(
            model_name='wastepickup',
            name='waste_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste_generators.wastesource'),
        ),
    ]
