# Generated by Django 5.2 on 2025-04-23 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_generators', '0004_foodtype_wastepickup_delete_generatortype_and_more'),
        ('waste_source_group', '0003_mastersource_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wastesource',
            name='generator',
        ),
        migrations.AddField(
            model_name='wastesource',
            name='waste_source',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='waste_source_group.mastersource'),
            preserve_default=False,
        ),
    ]
