# Generated by Django 5.2 on 2025-05-03 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_address'),
        ('waste_generators', '0005_remove_wastesource_generator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wastesourcemaster',
            name='location',
        ),
        migrations.AddField(
            model_name='wastesourcemaster',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.address'),
        ),
        migrations.AddField(
            model_name='wastesourcemaster',
            name='contact_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='wastesourcemaster',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wastesourcemaster',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
