# Generated by Django 5.2 on 2025-05-06 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_commoditygroup_status'),
        ('waste_collectors', '0002_remove_collector_address_line_1_and_more'),
        ('waste_generators', '0006_remove_wastesourcemaster_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastesource',
            name='food_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.commoditymater'),
        ),
        migrations.AlterField(
            model_name='wastepickup',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste_collectors.collector'),
        ),
        migrations.DeleteModel(
            name='FoodType',
        ),
    ]
