# Generated by Django 5.2 on 2025-07-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_generators', '0007_alter_wastesource_food_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastepickup',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='waste_pickup'),
        ),
    ]
