# Generated by Django 5.2 on 2025-05-03 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_address'),
        ('waste_collectors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collector',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='collector',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='collector',
            name='city',
        ),
        migrations.RemoveField(
            model_name='collector',
            name='pin_code',
        ),
        migrations.RemoveField(
            model_name='collector',
            name='state',
        ),
        migrations.AddField(
            model_name='collector',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.address'),
        ),
    ]
