# Generated by Django 5.2 on 2025-04-22 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0002_initial'),
        ('waste_source_group', '0003_mastersource_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_location', to='waste_source_group.mastersource'),
        ),
    ]
