# Generated by Django 5.2 on 2025-04-22 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0003_alter_audit_location'),
        ('waste_generators', '0003_alter_wastesourcemaster_waste_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste_generators.wastesourcemaster'),
        ),
    ]
