# Generated by Django 5.2 on 2025-05-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0004_alter_audit_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='scheduled_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
