# Generated by Django 5.2 on 2025-05-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0005_alter_audit_end_time_alter_audit_scheduled_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
