# Generated by Django 5.2 on 2025-05-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0006_audit_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='is_waiver_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audit',
            name='waiver_type',
            field=models.CharField(blank=True, choices=[('minimus', 'Minimus'), ('space', 'Space')], max_length=20, null=True),
        ),
    ]
