# Generated by Django 5.2 on 2025-07-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0010_alter_official_created_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditcommoditi',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='audit_item_images'),
        ),
    ]
