# Generated by Django 5.2 on 2025-04-22 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agreements', '0001_initial'),
        ('core', '0001_initial'),
        ('waste_collectors', '0001_initial'),
        ('waste_generators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='collector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste_collectors.collector'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='generator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste_generators.generator'),
        ),
        migrations.AddField(
            model_name='agreementitem',
            name='agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agreements.agreement'),
        ),
        migrations.AddField(
            model_name='agreementitem',
            name='commodity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.commoditymater'),
        ),
        migrations.AddField(
            model_name='agreementitem',
            name='measuring_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.measuringunitmaster'),
        ),
        migrations.AddField(
            model_name='agreementschedule',
            name='agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agreements.agreement'),
        ),
    ]
