# Generated by Django 5.2 on 2025-05-06 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0002_initial'),
        ('waste_generators', '0007_alter_wastesource_food_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='generator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste_generators.wastesourcemaster'),
        ),
    ]
