# Generated by Django 5.2 on 2025-05-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0003_alter_agreement_generator'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='expiration_date',
            field=models.DateField(default='2025-05-04'),
        ),
    ]
