# Generated by Django 5.2 on 2025-07-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_commoditymater_created_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measuringunitmaster',
            name='symbol',
            field=models.ImageField(max_length=255, upload_to='measuring_unit'),
        ),
    ]
