# Generated by Django 5.2 on 2025-07-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_message', models.TextField()),
                ('file_name', models.CharField(max_length=255)),
                ('line_number', models.IntegerField()),
                ('function_name', models.CharField(max_length=255)),
                ('error_line', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
