# Generated by Django 5.2 on 2025-04-22 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Official',
        ),
    ]
