# Generated by Django 5.2 on 2025-04-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_official'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('city_admin', 'City Admin'), ('auditor', 'Auditor'), ('regular', 'Regular User'), ('data_manager', 'Data Manager')], max_length=50),
        ),
    ]
