# Generated by Django 5.2 on 2025-04-29 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_user_type_role_code_role_restricted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='code',
        ),
    ]
