# Generated by Django 5.2 on 2025-07-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_module_remove_permission_module_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='company_logo',
            field=models.ImageField(blank=True, max_length=255, upload_to='company_logo'),
        ),
    ]
