# Generated by Django 5.2 on 2025-04-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_source_group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterdestination',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='mastersource',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=1),
        ),
    ]
