# Generated by Django 5.2 on 2025-04-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_source_group', '0002_alter_masterdestination_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastersource',
            name='code',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
